routes/web.php
<?php

//echo "--------------manggilroutesweb";

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if ( Auth::user() ) {
		return redirect()->route('home');
	} else {
    	return view('auth.login');
	}
});
Route::get('/login2', function () {
    return view('auth.login2');
});

Auth::routes();



Route::group(['middleware' => ['auth', 'verified',
	// 'user.activity'
]], function () { 

	//Dashboard
	Route::get('/dashboard', 'DashboardController@index')->name('home');
	Route::get('/abcd', 'CashboardController@index')->name('abcd');

	Route::get('/deliveries/{status}', 'ResponStatusController@mrspeedy');
	Route::get('/trackdemo/{appid}/{account}/{ref}/{hawb}', 'ResponStatusController@firstlogistic');

	Route::get('/sytem-log', 'DashboardController@systemLog')->name('dashboard.systemlog');
	Route::post('/sytem-log/get-all-json', 'DashboardController@getAllSystemLogJson')->name('dashboard.systemlogJson');
	
	// Send SMS
	Route::get('/sendsms', 'SendController@index');

	// List of Deliveries
	Route::get('/checkDOField/{field?}/{value?}','DeliveryController@checkFieldExist')->name('checkDOField');
	Route::post('/deliveryOrder/allList', 'DeliveryController@getAllListJson')->name('allDeliveries');
	Route::post('/deliveryOrder/ajaxOrderDelivered', 'DeliveryController@ajaxOrderDelivered')->name('ajaxOrderDelivered');
	Route::post('/deliveryOrder/ajaxOrderOverDue', 'DeliveryController@ajaxOrderOverDue')->name('ajaxOrderOverDue');

	// Delivery Order
	Route::group(['middleware' => ['can:view_delivery']], function () {
		Route::get('/delivery-order', 'DeliveryController@index')->name('list-pickup');
		Route::get('delivery-order/detail/{id}', 'DeliveryController@detailPickup')->name('detail_pickup');
		Route::get('/delivery-order/doubleDO/{order_id}', 'DeliveryController@doubleDO')->name('doubleDO');
		Route::get('/delivery-order/filterDO', 'DeliveryController@filterDO')->name('filterDO');	   
		Route::post('/delivery-order/filterDO', 'DeliveryController@filterDO')->name('filterDO');
		//get template for delivery order page, added by Ryan 02/09/2020
		Route::get('/delivery-order/template', 'DeliveryController@getTemplate')->name('delivery.getTemplate');	   
	});


	Route::group(['middleware' => ['can:create_delivery']], function () {
		Route::post('/importExcel', 'DeliveryController@import_excel')->name('importExcel');
		Route::get('delivery-order/add', 'DeliveryController@createlist')->name('createlist');
		Route::post('/createlist/store', 'DeliveryController@store')->name('storedata');
		Route::get('/delivery-order/preview', 'DeliveryController@uploadDataPreview')->name('preview');
		Route::get('/delivery-order/savedo', 'DeliveryController@saveDO')->name('save-do');
		Route::get('/delivery-order/cancelpreviewdo', 'DeliveryController@cancelPreviewDO')->name('cancelPreviewDo');
	});
	
	Route::group(['middleware' => ['can:edit_delivery']], function () {
		Route::get('/delivery-order/edit/{id}', 'DeliveryController@editDO')->name('edit_do');
		Route::post('/delivery-order/saveeditdo/{id}', 'DeliveryController@saveEditDO')->name('saveEditDO');
	});
	


	// LOST Function in Controller
	// Route::get('/previewexcel', 'DeliveryController@previewexcel')->name('previewexcel');
	// Route::get('/saveexcel', 'DeliveryController@saveexcel')->name('saveexcel');
	// Route::post('/createlist', 'DeliveryController@cancelpreview')->name('cancelpreview');
	// Route::post('/delivery-order/status/{id}', 'DeliveryController@manualstatus')->name('statusmanual');


	//Ticket
	
	Route::group(['middleware' => ['can:view_ticket_delivery']], function () {
		Route::get('/complain-ticket/delivery/{id?}', 'TicketController@index')->name('listticket');
		Route::get('/complain-ticket/non-delivery/{id?}', 'TicketController@nonDVIndex')->name('ticket.nonDVListticket');
		Route::get('/ticket/release/{id?}', 'TicketController@release')->name('releaseticket');
	});
	
	Route::group(['middleware' => ['can:edit_ticket_delivery']], function () {
		Route::get('/ticket/list-ticket/filterTicket', 'TicketController@filterTicket')->name('filterTicket');
		Route::get('/detailticketdo/{order_id}', 'TicketController@detailcomplaindo')->name('detailcomplaindo');
		Route::post('/storeeditticket/{id}', 'TicketController@storeeditticket')->name('storeeditticket');
		Route::get('/complain-ticket/reopenticket/{id}', 'TicketController@reopenticket')->name('re-open');
	});
	
	Route::get('/complain-ticket/detail/{id}', 'TicketController@detailticket')->name('detailticket');
	
	Route::group(['middleware' => ['can:create_ticket_delivery']], function () {
		Route::get('/complain-ticket/add/{id?}', 'TicketController@ticket')->name('newticket');
		Route::post('/ticket/addticket', 'TicketController@storeticket')->name('addticket');
		Route::get('/getticketbyso/{id}','TicketController@getsoDetail')->name('getsodetail');
	});

	Route::post('/complain-ticket/allList', 'TicketController@getAllListJson')->name('allTicket');
	Route::post('/complain-ticket/all-not-solved-list','TicketController@getAllNotResolvedJson')->name('allNotSolvedTicket');

	Route::get('/nondelivery','TicketController@nondelivticket')->name('nondeliv');

	//Performance
	// Route::get('/performance-vendor', 'PerfomVendorController@index')->name('performance_vendor');
	Route::get('/performance-vendor/export', 'PerfomVendorController@exportVD')->name('export_vendor');
	Route::get('/performance-vendor/detail/{id}', 'PerfomVendorController@detailVD')->name('vendordetail');
	Route::get('/performance-vendor/filterZN', 'PerfomVendorController@filterVD')->name('filterzona');

	// Performance version 2
	Route::get('/performance/leadtime', 'Performance\PerformanceController@index')->name('performance.leadtime');
	Route::get('/performance/leadtime/download/{courier}/{courier_id}/{startDate}/{endDate}', 'Performance\PerformanceController@downloadUnfulfilled')->name('performance.leadtime.provider.download');
	Route::post('/performance/leadtime', 'Performance\PerformanceController@index')->name('performance.leadtime');
	Route::get('/performance/leadtime/provider/{pid}/{startDate?}/{endDate?}', 'Performance\PerformanceController@providerLeadTime')->name('performance.leadtime.provider');
	Route::get('/performance/leadtime/zone/{pid}/{zid}/{startDate?}/{endDate?}', 'Performance\PerformanceController@zoneLeadTime')->name('performance.leadtime.zone');

	Route::get('/performance/successrate', 'Performance\PerformanceController@successRate')->name('performance.successrate');
	Route::post('/performance/successrate', 'Performance\PerformanceController@successRate')->name('performance.successrate');
	Route::get('/performance/successrate/download/{courier}/{courier_id}/{startDate}/{endDate}', 'Performance\PerformanceController@downloadUndelivered')->name('performance.successrate.provider.download');
	Route::get('/performance/successrate/provider/{pid}', 'Performance\PerformanceController@providerSuccessRate')->name('performance.successrate.provider');
	Route::get('/performance/successrate/zone/{pid}/{zid}', 'Performance\PerformanceController@zoneSuccessRate')->name('performance.successrate.zone');

	Route::get('/checkDOField/{field?}/{value?}','DeliveryController@checkFieldExist')->name('checkDOField');


	
	Route::resource('/settings/postalcodes','PostalCodeController');
	Route::get('/settings/postalcodes/check-code/{code}','PostalCodeController@checkCode')->name('postalCode.checkCode');

	Route::resource('/settings/zones','ZoneController');
	Route::resource('/settings/stores','StoreController');
	Route::resource('/settings/provinces','ProvinceController');
	Route::resource('/settings/cities','CityController');
	Route::resource('/settings/holidays','HolidayController');
	Route::resource('/settings/nuskinstatus','NuskinStatusController');
	Route::resource('/settings/couriers','CourierController');
	Route::get('/settings/couriers/change-active/{id}', 'CourierController@changeActive')->name('courier.change'); //Post and Unpost

	Route::resource('/settings/courierstatus','CourierStatusController');
	Route::post('/settings/postalcodes/importExcel', 'PostalCodeController@import_excel')->name('importExcelPostal');
	Route::post('/settings/postalcodes/importExcelCourier', 'PostalCodeController@import_excel_courier')->name('importExcelCourier');
	Route::post('/settings/postalcodes/importExcelPostalCityProvince', 'PostalCodeController@import_excel_postalcityprovince')->name('importExcelPostalCityProvince');

	Route::get('/detailticket/{id}/{pid?}', 'TicketController@detailticket')->name('detailticket2');

    Route::resource('/settings/roles','RoleController');
    Route::resource('/settings/users','UserController');
	Route::get('/user-profile/{id}', 'UserController@userprofile')->name('profileuser');
	Route::post('/user-profile/{id}', 'UserController@updateprofile')->name('profileupdate');
    

	//User
	// Route::get('/user-menu', 'UserController@index')->name('usermenu');
	// Route::get('/user-menu/create', 'UserController@create')->name('usercreate');
	// Route::post('/user-menu/store', 'UserController@store')->name('userstore');
	// Route::get('/user-menu/edit/{id}', 'UserController@edit')->name('userdedit');
	// Route::get('/user-menu/destroy/{id}', 'UserController@destroy')->name('userdestroy');
	// Route::post('/user-menu/update/{id}', 'UserController@update')->name('userupdate');

	//Menu
	Route::get('/kelolamenu', 'KelolaMenu@index')->name('kelolamenu');
	Route::get('/kelolamenu/addMenu', 'KelolaMenu@addMenu')->name('add_menu_list');

	Route::get('/settings/topic', 'KelolaMenu@listtopics')->name('kelolatopics');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable
{
    use Notifiable, HasRoles;
    use LogsActivity;
	
    protected static $ignoreChangedAttributes = ['password','lastActivity','updated_at'];
	protected static $logUnguarded = true;
    protected static $logOnlyDirty = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','rolename','photo_path'
    ];
	/* 
    protected $guarded = ['id'];
	*/

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $guarded = ['id','password','lastActivity'];
    protected static $submitEmptyLogs = false;
}

resources/views/users/create.blade.php
@extends('layoutAdmin.global')

@section('content')
<div class="content-wrapper">
    <section class="p-2 pb-0">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <a href="{{ route('users.index')}}" class="text-muted"><i class="fas fa-long-arrow-alt-left"></i> Back to list</a>
          </div>
        </div>
      </div>
    </section>
    <!-- Content Header (Page header) -->
    <section class="content-header pt-0">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Create User</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('users.index')}}">Users Management</a></li>
                    <li class="breadcrumb-item active">Create User</li>
                </ol>
            </div>
        </div>
    </section>

    <section class="content">
      <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-9">
              @if (count($errors) > 0)
              <div class="alert alert-danger">
                  <p></p><strong>Whoops!</strong> There were some problems with your input.</p>
                  <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                 </ul>
              </div>
              @endif
              @if (session('error'))
                <div class="alert alert-danger">{!! session('error') !!}</div>
              @endif
              <div class="card">
                {!! Form::open(array('route' => 'users.store','method'=>'POST', 'files'=> true)) !!}
                    <div class="card-body">
                      <div class="col-xs-12 col-sm-12 col-md-12">
                          <div class="form-group">
                              <strong>Name</strong>
                              {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                          </div>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12">
                          <div class="form-group">
                              <strong>Email</strong>
                              {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                          </div>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12">
                          <div class="form-group">
                              <strong>Photo</strong>
                              {!! Form::file('image', array('class' => 'form-control')) !!}
                          </div>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12">
                          <div class="form-group">
                              <strong>Password</strong>
                              {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
                          </div>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12">
                          <div class="form-group">
                              <strong>Confirm Password</strong>
                              {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
                          </div>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12">
                          <div class="form-group">
                              <strong>Role</strong>
                              <div class="col-xs-12">
                              @foreach($roles  as $role)
                                  <label>{{ Form::checkbox('roles[]', $role , false, array('class' => 'name')) }}
                                  {{ $role  }}</label>
                                  @error('roles')
                                      <div class="invalid-feedback">{{ $message }}</div>
                                  @enderror
                              @endforeach
                              </div>
                              {{-- <select name="roles" id="topic" class="form-control @error('roles') is-invalid @enderror select2" style="width: 100%;" value="{{ old('roles') }}">
                                <option value="" selected disabled hidden class="form-control  @error('roles') is-invalid @enderror">Select Roles</option>
                                  @foreach($roles  as $role)
                                    <option value="{{ $role }}">{{ $role }}</option>
                                    @error('roles')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                  @endforeach
                              </select> --}}
                          </div>
                      </div>
                    
                    </div>
                    <div class="card-footer">
                            <a href="{{ route('users.index')}}" class="btn btn-default mr-2 mb-2"><i class="fas fa-times"></i> Cancel</a>
                            <div class="float-right"><button type="submit" class="btn btn-info mb-2"> Submit </button></div>
                    </div>
                {!! Form::close() !!}
              </div>
            </div>
        </div>
      </div>
    </section>
</div>

@endsection

resources/views/users/edit.blade.php
@extends('layoutAdmin.global')

@section('content')
<div class="content-wrapper">

    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Edit User</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route('users.index')}}">Users Management</a></li>
                <li class="breadcrumb-item active">Edit User</li>
              </ol>
            </div>
          </div>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        @if (count($errors) > 0)
                          <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                               @foreach ($errors->all() as $error)
                                 <li>{{ $error }}</li>
                               @endforeach
                            </ul>
                          </div>
                        @endif

                        @if (session('error'))
                            <div class="alert alert-danger">{!! session('error') !!}</div>
                        @endif
                        {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id], 'files'=> true]) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Email</strong>
                                    {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Photo</strong>
                                    <br>
                                    @if($user->photo_path)
                                    <img alt="{{$user->name}}" class="img img-size-128 mr-2" src="{{ asset($user->photo_path) }}">
                                    @endif
                                    {!! Form::file('image', null, array('class' => 'form-control')) !!}
                                    {!! Form::hidden('photo_path', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Password</strong>
                                    {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Confirm Password:</strong>
                                    {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Role</strong>
                                    <div class="col-xs-12">
                                    @foreach($roles  as $role)
                                        <label>{{ Form::checkbox('roles[]', $role , in_array($role, $namerole) ? true : false, array('class' => 'name')) }}
                                        {{ $role  }}</label>
                                        @error('roles')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                    @endforeach
                                    </div>
                                    {{-- <select name="roles" id="topic" class="form-control @error('roles') is-invalid @enderror select2" style="width: 100%;" value="{{ old('roles') }}">
                                            <option value="{{ $namerole }}" hidden class="form-control  @error('roles') is-invalid @enderror">{{ $namerole }}</option>
                                        @foreach($roles  as $role)
                                                <option value="{{ $role }}">{{ $role }}</option>
                                          @error('roles')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                          @enderror
                                        @endforeach
                                    </select> --}}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="card-footer">
                                    <div class="row">
                                    <a href="{{ route('users.index')}}" class="btn btn-default mr-2 mb-2">Cancel</a>
                                    <button type="submit" class="btn btn-info mb-2"> Submit </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </section>

</div>
@endsection

resources/views/users/index.blade.php
@extends('layoutAdmin.global')

@section('content')
<div class="content-wrapper">

  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Users Management</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
            <li class="breadcrumb-item">Settings</li>
            <li class="breadcrumb-item active">Users Management</li>
          </ol>
        </div>
      </div>
    </div>
  </section>

  <section class="content">
      <div class="container">
          <div class="row justify-content-md-center">
              <div class="col-12 col-md-10">
                  <div class="card">
                      <div class="card-header">
                        @if (session('error'))
                          <div class="alert alert-danger">{{ session('error') }}</div>
                        @endif
                          @can('create_setting')
                          <a href="{{ route('users.create') }}" class="btn btn-primary mr-3">
                            <i class="fas fa-plus mr-1"></i>Create User
                          </a>
                          @endcan
                      </div>
                      <div class="card-body">
                          @if ($message = Session::get('success'))
                          <div class="alert alert-success alert-block">
                              <button type="button" class="close" data-dismiss="alert">×</button>
                              <p style="color: #fff;">{{ $message }}</p>
                          </div>
                          @endif
  
                          <table id="usermanage" class="table" style="border:1px solid #ddd">
                              <thead class="thead-light">
                                  <tr>
                                      <th>User Name</th>
                                      <th>Email</th>
                                      <th>Roles</th>
                                      <th width="100px" class="text-center">Action</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  @php $i=0
                                  @endphp
                                  @foreach ($data as $key => $user)
                                  <tr>
                                      <td>
                                          @if($user->photo_path)
                                          <img alt="{{$user->name}}" class="img-circle img-size-32 mr-2" src="{{ asset($user->photo_path) }}">
                                          <a href="#"><strong>{{ $user->name }}</strong></a>
                                          @else
                                          <img alt="{{$user->name}}" class="img-circle img-size-32 mr-2" src="{{ asset('image/avatar/avatar6.png') }}">
                                          <a href="#"><strong>{{ $user->name }}</strong></a>
                                          @endif
                                      </td>
                                      <td><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></td>
                                      <td>
                                          @if(!empty($user->getRoleNames())) @foreach($user->getRoleNames() as $v)
                                          <label class="badge badge-secondary">{{ $v }}</label> @endforeach @endif
                                      </td>
                                      <td class="text-right">
                                          <a class="btn btn-success btn-xs" href="{{ route('users.show',$user->id) }}" data-toggle='tooltip' title='Detail'><i class="fas fa-info-circle"></i></a> @can('edit_setting')
                                          <a class="btn btn-warning btn-xs" href="{{ route('users.edit',$user->id) }}" data-toggle='tooltip' title='Edit'><i class="fas fa-edit"></i></a> @endcan @can('delete_setting') {!! Form::open(['method' => 'DELETE','route'
                                          => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                                          <button type="submit" class="btn btn-danger btn-xs" data-toggle='tooltip' title='Delete' onclick="myFunction()"><i class="fas fa-trash"></i></button> {!! Form::close() !!} @endcan
                                      </td>
                                  </tr>
                                  @endforeach
                              </tbody>
                          </table>
  
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
</div>

@endsection

@section('scripts')
  <script type="text/javascript">
    $(function () {
      $('#usermanage').DataTable();
    });

    function myFunction() {
      confirm("Are you sure you want to delete this user?");
    }
  </script>
@endsection

resources/views/users/show.blade.php
@extends('layoutAdmin.global')

@section('content')
<div class="content-wrapper">

    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Detail User</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route('users.index')}}">Users Management</a></li>
                <li class="breadcrumb-item active">Detail Role</li>
              </ol>
            </div>
          </div>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Name:</strong>
                                {{ $user->name }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Email:</strong>
                                {{ $user->email }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Roles:</strong>
                                @if(!empty($user->getRoleNames()))
                                    @foreach($user->getRoleNames() as $v)
                                        <label class="badge badge-secondary">{{ $v }}</label>
                                    @endforeach
                                @endif
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <a href="{{ route('users.index')}}" class="btn btn-default">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@endsection