routes/web.php
	Route::group(['middleware' => ['can:edit_ticket_delivery']], function () {
		Route::get('/ticket/list-ticket/filterTicket', 'TicketController@filterTicket')->name('filterTicket');
		Route::get('/detailticketdo/{order_id}', 'TicketController@detailcomplaindo')->name('detailcomplaindo');
		Route::post('/storeeditticket/{id}', 'TicketController@storeeditticket')->name('storeeditticket');
		Route::get('/complain-ticket/reopenticket/{id}', 'TicketController@reopenticket')->name('re-open');
	});
	
	Route::get('/complain-ticket/detail/{id}', 'TicketController@detailticket')->name('detailticket');
	
	Route::group(['middleware' => ['can:create_ticket_delivery']], function () {
		Route::get('/complain-ticket/add/{id?}', 'TicketController@ticket')->name('newticket');
		Route::post('/ticket/addticket', 'TicketController@storeticket')->name('addticket');
		Route::get('/getticketbyso/{id}','TicketController@getsoDetail')->name('getsodetail');
	});

	Route::post('/complain-ticket/allList', 'TicketController@getAllListJson')->name('allTicket');
	Route::post('/complain-ticket/all-not-solved-list','TicketController@getAllNotResolvedJson')->name('allNotSolvedTicket');

	Route::get('/nondelivery','TicketController@nondelivticket')->name('nondeliv');

	//Performance
	// Route::get('/performance-vendor', 'PerfomVendorController@index')->name('performance_vendor');
	Route::get('/performance-vendor/export', 'PerfomVendorController@exportVD')->name('export_vendor');
	Route::get('/performance-vendor/detail/{id}', 'PerfomVendorController@detailVD')->name('vendordetail');
	Route::get('/performance-vendor/filterZN', 'PerfomVendorController@filterVD')->name('filterzona');

	// Performance version 2
	Route::get('/performance/leadtime', 'Performance\PerformanceController@index')->name('performance.leadtime');
	Route::get('/performance/leadtime/download/{courier}/{courier_id}/{startDate}/{endDate}', 'Performance\PerformanceController@downloadUnfulfilled')->name('performance.leadtime.provider.download');
	Route::post('/performance/leadtime', 'Performance\PerformanceController@index')->name('performance.leadtime');
	Route::get('/performance/leadtime/provider/{pid}/{startDate?}/{endDate?}', 'Performance\PerformanceController@providerLeadTime')->name('performance.leadtime.provider');
	Route::get('/performance/leadtime/zone/{pid}/{zid}/{startDate?}/{endDate?}', 'Performance\PerformanceController@zoneLeadTime')->name('performance.leadtime.zone');

	Route::get('/performance/successrate', 'Performance\PerformanceController@successRate')->name('performance.successrate');
	Route::post('/performance/successrate', 'Performance\PerformanceController@successRate')->name('performance.successrate');
	Route::get('/performance/successrate/download/{courier}/{courier_id}/{startDate}/{endDate}', 'Performance\PerformanceController@downloadUndelivered')->name('performance.successrate.provider.download');
	Route::get('/performance/successrate/provider/{pid}', 'Performance\PerformanceController@providerSuccessRate')->name('performance.successrate.provider');
	Route::get('/performance/successrate/zone/{pid}/{zid}', 'Performance\PerformanceController@zoneSuccessRate')->name('performance.successrate.zone');

	Route::get('/checkDOField/{field?}/{value?}','DeliveryController@checkFieldExist')->name('checkDOField');


	
	Route::resource('/settings/postalcodes','PostalCodeController');
	Route::get('/settings/postalcodes/check-code/{code}','PostalCodeController@checkCode')->name('postalCode.checkCode');

	Route::resource('/settings/zones','ZoneController');
	Route::resource('/settings/stores','StoreController');
	Route::resource('/settings/provinces','ProvinceController');
	Route::resource('/settings/cities','CityController');
	Route::resource('/settings/holidays','HolidayController');
	Route::resource('/settings/nuskinstatus','NuskinStatusController');
	Route::resource('/settings/couriers','CourierController');
	Route::get('/settings/couriers/change-active/{id}', 'CourierController@changeActive')->name('courier.change'); //Post and Unpost

	Route::resource('/settings/courierstatus','CourierStatusController');
	Route::post('/settings/postalcodes/importExcel', 'PostalCodeController@import_excel')->name('importExcelPostal');
	Route::post('/settings/postalcodes/importExcelCourier', 'PostalCodeController@import_excel_courier')->name('importExcelCourier');
	Route::post('/settings/postalcodes/importExcelPostalCityProvince', 'PostalCodeController@import_excel_postalcityprovince')->name('importExcelPostalCityProvince');

	Route::get('/detailticket/{id}/{pid?}', 'TicketController@detailticket')->name('detailticket2');

    Route::resource('/settings/roles','RoleController');
    Route::resource('/settings/users','UserController');
	Route::get('/user-profile/{id}', 'UserController@userprofile')->name('profileuser');
	Route::post('/user-profile/{id}', 'UserController@updateprofile')->name('profileupdate');
    

	//User
	// Route::get('/user-menu', 'UserController@index')->name('usermenu');
	// Route::get('/user-menu/create', 'UserController@create')->name('usercreate');
	// Route::post('/user-menu/store', 'UserController@store')->name('userstore');
	// Route::get('/user-menu/edit/{id}', 'UserController@edit')->name('userdedit');
	// Route::get('/user-menu/destroy/{id}', 'UserController@destroy')->name('userdestroy');
	// Route::post('/user-menu/update/{id}', 'UserController@update')->name('userupdate');

	//Menu
	Route::get('/kelolamenu', 'KelolaMenu@index')->name('kelolamenu');
	Route::get('/kelolamenu/addMenu', 'KelolaMenu@addMenu')->name('add_menu_list');

	Route::get('/settings/topic', 'KelolaMenu@listtopics')->name('kelolatopics');
	Route::get('/settings/topic/add', 'KelolaMenu@addtopics')->name('createtopics');
	Route::post('/settings/storetopic', 'KelolaMenu@storetopics')->name('storetopics');
	Route::get('/settings/topic/edit/{id}', 'KelolaMenu@edittopics')->name('edittopics');
	Route::post('/settings/edittopic/{id}', 'KelolaMenu@storeedit')->name('edittopic');
	Route::get('/settings/deletetopic/{id}', 'KelolaMenu@destroy')->name('deletetopics');

	//kelolakodepos
	Route::get('/kelolakodepos', 'KelolaMenu@indexpos')->name('kelolakodepos');
	Route::post('/kelolakodepos/importExcel', 'KelolaMenu@importexcel')->name('importzip');
	Route::get('/kelolakodepos/createkode', 'KelolaMenu@createkode')->name('createkode');
	Route::post('/kelolakodepos/add-kode', 'KelolaMenu@addkode')->name('add-kode');
	Route::get('/kelolakodepos/editkode/{id}', 'KelolaMenu@nameeditkode')->name('kodeposedit');
	Route::post('/kelolakodepos/storeeditkode/{id}', 'KelolaMenu@storeeditkode')->name('storeeditkode');
	Route::get('/kelolakodepos/deletekode/{id}', 'KelolaMenu@destroykode')->name('destroykode');

	//Warehouse
	// Route::get('/settings/warehouse', 'KelolaRole@index')->name('kelolarole');
	// Route::get('/settings/warehouse/add', 'KelolaRole@gudang')->name('newgudang');
	// Route::post('/settings/addgudang', 'KelolaRole@addGudang')->name('add-gudang');
	// Route::get('/settings/warehouse/edit/{id_gudang}', 'KelolaRole@editgudang')->name('editgudangs');
	// Route::post('/settings/editgudang/{id_gudang}', 'KelolaRole@storegudang')->name('editgudang');
	// Route::get('/settings/delete/{id_gudang}', 'KelolaRole@destroy')->name('deletegudang');

	Route::get('/settings/warehouse', 'WarehouseController@index')->name('kelolarole');
	Route::get('/settings/warehouse/add', 'WarehouseController@gudang')->name('newgudang');
	Route::post('/settings/addgudang', 'WarehouseController@addGudang')->name('add-gudang');
	Route::get('/settings/warehouse/edit/{id_gudang}', 'WarehouseController@editgudang')->name('editgudangs');
	Route::post('/settings/editgudang/{id_gudang}', 'WarehouseController@storegudang')->name('editgudang');
	Route::delete('/settings/warehouse/delete/{id_gudang}', 'WarehouseController@destroy')->name('deletegudang');
	Route::post('settings/warehouse/getAllListJson', 'WarehouseController@getAllListJson')->name('warehouse.getAllListJson');

	Route::post('settings/warehouse/get-warehouse', 'WarehouseController@getWarehouse')->name('warehouse.getWarehouse');

	//Vendor
	Route::get('/listvendor', 'ListVendor@index')->name('list-vendor');

	//Zonasi
	Route::get('/list-zonasi', 'ListZonasi@index')->name('listzonasi');
	Route::get('/home/list-zonasi/create-zonasi', 'ListZonasi@addZonasi')->name('listzonasi.create');
	Route::post('/home/list-zonasi/store-zonasi', 'ListZonasi@storeZonasi')->name('listzonasi.add');
	Route::get('/home/list-zonasi/edit-zonasi/{id}', 'ListZonasi@editZonasi')->name('listzonasi.edit');
	Route::post('/home/list-zonasi/store-edit/{id}', 'ListZonasi@storeedit')->name('listzonasi.storeedit');
	Route::get('/home/list-zonasi/destroy-zonasi/{id}', 'ListZonasi@destroyZonasi')->name('listzonasi.delete');

	//Master Vendor
	Route::get('/master-vendor', 'MasterVendor@index')->name('list-mastervendor');
	Route::get('/master-vendor/create-mastervendor', 'MasterVendor@addVendor')->name('list-mastervendor.create');
	Route::post('/master-vendor/store-mastervendor', 'MasterVendor@storeVendor')->name('list-mastervendor.add');
	Route::get('/master-vendor/edit-mastervendor/{id}', 'MasterVendor@editVendor')->name('list-mastervendor.edit');
	Route::post('/master-vendor/store-edit/{id}', 'MasterVendor@storeedit')->name('list-mastervendor.storeedit');
	Route::get('/master-vendor/destroy-mastervendor/{id}', 'MasterVendor@destroyMasterVendor')->name('list-mastervendor.delete');

	//Kelola Vendor
	Route::get('/kelola-vendor', 'KelolaVendor@index')->name('list-kelolavendor');
	Route::get('/kelola-vendor/create-kelolavendor', 'KelolaVendor@addVendor')->name('list-kelolavendor.create');
	Route::post('/kelola-vendor/store-kelolavendor', 'KelolaVendor@storeVendor')->name('list-kelolavendor.add');
	Route::get('/kelola-vendor/edit-kelolavendor/{id}', 'KelolaVendor@editVendor')->name('list-kelolavendor.edit');

resources/views/settings/city.blade.php
@extends('layoutAdmin.global')


@section('content')

<?php $model_name = "City"; ?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ $model_name }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
              <li class="breadcrumb-item active">{{ $model_name }}</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
	
    <!-- Main content -->
    <section class="content">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-12 col-md-9">
            @if ($errors->any())
  					<div class="alert alert-danger">
  						<ul>
  							@foreach ($errors->all() as $error)
  								<li>{{ $error }}</li>
  							@endforeach
  						</ul>
  					</div>
  				  @endif
            <div class="card">
              <div class="card-header">
              @can('create_setting')
				  	  	<a class="btn btn-primary" href="javascript:void(0)" id="createNewItem">Create New {{ $model_name }}</a>
      				@endcan
              </div>
              <div class="card-body">
        				<table class="table text-nowrap data-table">
        					<thead class="thead-light">
        						<tr>
        							<th width="10px">No</th>
        							<th>Name</th>
        							<th>Province</th>
        							<th width="50px">Action</th>
        						</tr>
        					</thead>
        					<tbody>
        					</tbody>
        				</table>
        			</div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
    </section>
    <!-- /.content -->
</div>
   
<div class="modal fade" id="ajaxModel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="itemForm" name="itemForm" class="form-horizontal">
                   <input type="hidden" name="model_id" id="model_id">
				   
                    <div class="form-group row">
                        <label for="name" class="col-sm-3 control-label">Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter {{ $model_name }} Name" required>
                        </div>
                    </div>
					
                    <div class="form-group row">
                        <label for="province_id" class="col-sm-3 control-label">Province</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="province_id" name="province_id" required >
								<option value="" selected disabled hidden >-- Select Province --</option>
								  @foreach($provinces as  $province)
								  <option value="{{ $province->id }}">{{ $province->name }}</option>
								  @endforeach
							</select>
                        </div>
                    </div>
      
                    <div class="form-group">
                     <button type="submit" class="btn btn-info float-right" id="saveBtn" value="create">Save
                     </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    

@endsection




@section('scripts')
    
<script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table = $('.data-table').DataTable({
			"fnDrawCallback": function( oSettings ) {
					  $('[data-toggle="tooltip"]').tooltip({
							trigger : 'hover'
						});
					},
		//responsive: true,
		"language": {
            processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span> '},
		
        processing: true,
        serverSide: true,
        ajax: "{{ route('cities.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'province.name', name: 'province.name', orderable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
     
    $('#createNewItem').click(function () {
        $('#saveBtn').val("create...");
        $('#model_id').val('');
        $('#itemForm').trigger("reset");
        $('#modelHeading').html("Create New {{ $model_name }}");
        $('#ajaxModel').modal('show');
    });
    
    $('body').on('click', '.editProduct', function () {
      var model_id = $(this).data('id');
      $.get("{{ route('cities.index') }}" +'/' + model_id +'/edit', function (data) {
		  $('#modelHeading').html("Edit {{ $model_name }}");
          $('#saveBtn').val("edit...");
          $('#ajaxModel').modal('show');
		  
          $('#model_id').val(data.id);
          $('#name').val(data.name);
          $('#province_id').val(data.province_id);
      })
   });
    
    $('#saveBtn').click(function (e) {
    
		let isValidForm = $('#itemForm')[0].checkValidity();
		if(isValidForm){
			e.preventDefault();
			$(this).html('Sending..');
							
			$.ajax({
			  data: $('#itemForm').serialize(),
			  url: "{{ route('cities.store') }}",
			  type: "POST",
			  dataType: 'json',
			  success: function (data) {
				  $('#saveBtn').html('Save');
				  $('#itemForm').trigger("reset");
				  $('#ajaxModel').modal('hide');
				  table.draw();
				  toastr.success(data.success);
			 
			  },
			  error: function (data) {
				  console.log('Error:', data);
				  $('#saveBtn').html('Save');
			  }
		  });
			
		}
    });
    
    $('body').on('click', '.deleteProduct', function () {
     
        var model_id = $(this).data("id");
		
		
		Swal.fire({
			title: 'Are you sure you want to Delete?',
			text: "You won't be able to revert this!",
			type: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: 'Yes!'
		  }).then((result) => {
			if (result.value) { //yes
			  $.ajax({
					type: "DELETE",
					url: "{{ route('cities.store') }}"+'/'+model_id,
					success: function (data) {
						table.draw();
					  toastr.success(data.success);
					},
					error: function (data) {
						console.log('Error:', data);
					}
				});;
			}
		  })
    });
     
  });
  
  
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
		trigger : 'hover'
	});
	
	/*
	$('select').select2({
		theme: 'bootstrap4',
	});
	*/
});
</script>


@endsection

resources/views/settings/courier.blade.php
@extends('layoutAdmin.global')


@section('content')

<?php $model_name = "Courier"; ?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ $model_name }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              <li class="breadcrumb-item active">{{ $model_name }}</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
  
    <!-- Main content -->
    <section class="content">
      <div class="container">
        <div class="row">
          <div class="col-12">
            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                  @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                  @endforeach
                </ul>
              </div>
            @endif
            <div class="card">
              <div class="card-header">
                @can('create_setting')
                  <a class="btn btn-primary" href="javascript:void(0)" id="createNewItem">
                    <i class="fas fa-plus mr-1"></i>Create New {{ $model_name }}
                  </a>
                @endcan
              </div>
              <div class="card-body">
                <table class="table text-nowrap data-table" style="border:1px solid #ddd">
                  <thead class="thead-light">
                    <tr>
                      <th>No</th>
                      <th>Name</th>
                      <th>Code</th>
                      <th>Display Name</th>
                      <th>PIC</th>
                      <th>PIC's Email</th>
                      <th>SMS Notification</th>
                      <th>Check Status</th>
                      <th width="5%">Active</th>
                      <th width="5%" class="text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
    </section>
    <!-- /.content -->
</div>
   
<div class="modal fade" id="ajaxModel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="itemForm" name="itemForm" class="form-horizontal">
                   <input type="hidden" name="model_id" id="model_id">
           
                    <div class="form-group row">
                        <label for="name" class="col-sm-3 control-label">Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter {{ $model_name }} Name" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="code" class="col-sm-3 control-label">Code</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="code" name="code" placeholder="Enter {{ $model_name }} Code" required >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="code" class="col-sm-3 control-label">Display Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="display_name" name="display_name" placeholder="Enter Display Name" required >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="code" class="col-sm-3 control-label">PIC</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="pic" name="pic" placeholder="Enter PIC Name" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="code" class="col-sm-3 control-label">PIC's Email</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="pic_email" name="pic_email" placeholder="Enter PIC's Email" >
                        </div>
                    </div>
                    <div class="form-group row custom-switch">
                      <input type="checkbox" class="custom-control-input" id="is_sms_notification" name="is_sms_notification" value="1">
                      <label class="custom-control-label" for="is_sms_notification"> SMS Notification</label>
                    </div>
                    <div class="form-group row custom-control custom-switch">
                      <input type="checkbox" class="custom-control-input" id="is_delivery_check" name="is_delivery_check" value="1">
                      <label class="custom-control-label" for="is_delivery_check"> Check Delivery Status</label>
                    </div>
      
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-info" id="saveBtn" value="create">Save
                      </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    

@endsection




@section('scripts')
    
<script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table = $('.data-table').DataTable({
      responsive: true,
      "scrollX":true,
      "fixedColumns": {
        "leftColumns": 2
      },
      "fnDrawCallback": function( oSettings ) {
            $('[data-toggle="tooltip"]').tooltip({
              trigger : 'hover'
            });
          },
        processing: true,
    "language": {
            processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span> '},
        
        serverSide: true,

        ajax: "{{ route('couriers.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'code', name: 'code'},
            {data: 'display_name', name: 'display_name'},
            {data: 'pic', name: 'pic'},
            {data: 'pic_email', name: 'pic_email'},
            {data: 'is_sms_notification', name: 'is_sms_notification'},
            {data: 'is_delivery_check', name: 'is_delivery_check'},
            {data: 'active', name: 'active', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
     
    $('#createNewItem').click(function () {
        $('#saveBtn').val("create...");
        $('#model_id').val('');
        $('#itemForm').trigger("reset");
        $('#modelHeading').html("Create New {{ $model_name }}");
        $('#ajaxModel').modal('show');
    });
    
    $('body').on('click', '.editProduct', function () {
      var model_id = $(this).data('id');
      $.get("{{ route('couriers.index') }}" +'/' + model_id +'/edit', function (data) {
      $('#modelHeading').html("Edit {{ $model_name }}");
          $('#saveBtn').val("edit...");
          $('#ajaxModel').modal('show');
            
          $('#model_id').val(data.id);
          $('#name').val(data.name);
          $('#code').val(data.code);
          $('#display_name').val(data.display_name);
          $('#pic').val(data.pic);
          $('#pic_email').val(data.pic_email);
      
      $('#is_sms_notification').prop("checked", data.is_sms_notification);
      $('#is_delivery_check').prop("checked", data.is_delivery_check);
      
      })
   });
    
    $('#saveBtn').click(function (e) {
    
    let isValidForm = $('#itemForm')[0].checkValidity();
    if(isValidForm){
      e.preventDefault();
      $(this).html('Sending..');
              
      $.ajax({
        data: $('#itemForm').serialize(),
        url: "{{ route('couriers.store') }}",
        type: "POST",
        dataType: 'json',
        success: function (data) {
          $('#saveBtn').html('Save');
          $('#itemForm').trigger("reset");
          $('#ajaxModel').modal('hide');
          table.draw();
          toastr.success(data.success);
       
        },
        error: function (data) {
          console.log('Error:', data);
          $('#saveBtn').html('Save');
        }
      });
      
    }
    });
    
    $('body').on('click', '.deleteProduct', function () {
     
        var model_id = $(this).data("id");
        
    Swal.fire({
        title: 'Are you sure you want to Delete?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes!'
      }).then((result) => {
        if (result.value) { //yes
          $.ajax({
        type: "DELETE",
        url: "{{ route('couriers.store') }}"+'/'+model_id,
        success: function (data) {
          table.draw();
          toastr.success(data.success);
        },
        error: function (data) {
          console.log('Error:', data);
        }
      });;
        }
      })
    
    /*
    let abc = confirm("Are You sure want to delete !");
    
    if (abc == true) {
      $.ajax({
        type: "DELETE",
        url: "{{ route('couriers.store') }}"+'/'+model_id,
        success: function (data) {
          table.draw();
          toastr.success(data.success);
        },
        error: function (data) {
          console.log('Error:', data);
        }
      });
    } else {
      ;
    }
    */
    
    });
     
  });
  
  
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
    trigger : 'hover'
  });
  
  /*
  $('select').select2({
    theme: 'bootstrap4',
  });
  */
});
</script>


@endsection